# Generated by Django 4.2.29 on 2026-04-02 05:07

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('sector', models.CharField(choices=[('banking', 'Banking & Finance'), ('realestate', 'Real Estate Market'), ('macro', 'Macroeconomics'), ('investment', 'Investment'), ('crypto', 'Crypto & Digital Assets'), ('regional', 'Western Balkans Region'), ('eu', 'EU Integration')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Analysis Category',
                'verbose_name_plural': 'Analysis Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('executive_sum', models.TextField(help_text='Executive summary shown in listing cards')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('cover_image', models.ImageField(blank=True, upload_to='analysis/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('premium', 'Premium')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('pdf_export', models.FileField(blank=True, upload_to='analysis/pdfs/')),
                ('reading_time_min', models.PositiveSmallIntegerField(default=5)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='analysis.analysiscategory')),
                ('tags', models.ManyToManyField(blank=True, to='news.newstag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_title', models.CharField(max_length=200)),
                ('chart_type', models.CharField(choices=[('line', 'Line'), ('bar', 'Bar'), ('pie', 'Pie'), ('doughnut', 'Doughnut'), ('area', 'Area')], default='line', max_length=10)),
                ('labels_json', models.JSONField(help_text='List of X-axis labels')),
                ('datasets_json', models.JSONField(help_text='Chart.js datasets array')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='analysis.analysisreport')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
