# Generated by Django 4.2.29 on 2026-04-05 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('rss_url', models.URLField(blank=True)),
                ('entity', models.CharField(choices=[('FBiH', 'Federacija BiH'), ('RS', 'Republika Srpska'), ('BD', 'Brčko distrikt'), ('national', 'Cijela BiH')], default='national', max_length=10)),
                ('portal_type', models.CharField(choices=[('online', 'Online portal'), ('tv', 'Televizija'), ('radio', 'Radio'), ('print', 'Stampa'), ('agency', 'Novinska agencija')], default='online', max_length=10)),
                ('rak_id', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('articles_collected', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Medijski portal',
                'verbose_name_plural': 'Medijski portali',
                'ordering': ['entity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('abbreviation', models.CharField(blank=True, max_length=30)),
                ('entity', models.CharField(choices=[('BiH', 'Bosna i Hercegovina'), ('FBiH', 'Federacija BiH'), ('RS', 'Republika Srpska'), ('BD', 'Brčko distrikt')], default='BiH', max_length=10)),
                ('ideology', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='politics/parties/')),
                ('cik_id', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Politicka stranka',
                'verbose_name_plural': 'Politicke stranke',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PoliticalFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('entity', models.CharField(choices=[('BiH', 'Bosna i Hercegovina'), ('FBiH', 'Federacija BiH'), ('RS', 'Republika Srpska'), ('BD', 'Brčko distrikt')], default='BiH', max_length=10)),
                ('current_position', models.CharField(blank=True, max_length=300)),
                ('photo', models.ImageField(blank=True, upload_to='politics/figures/')),
                ('name_variations', models.TextField(blank=True, help_text='Varijante imena odvojene zarezom (za pretragu portalima)')),
                ('cik_id', models.CharField(blank=True, max_length=50)),
                ('was_in_previous_cycle', models.BooleanField(default=False)),
                ('running_for', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figures', to='politics.politicalparty')),
            ],
            options={
                'verbose_name': 'Politicki akter',
                'verbose_name_plural': 'Politicki akteri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MentionScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('success', 'Uspjesno'), ('partial', 'Djelimicno'), ('failed', 'Neuspjesno')], max_length=10)),
                ('articles_checked', models.PositiveIntegerField(default=0)),
                ('mentions_found', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_logs', to='politics.mediaportal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoliticalMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article_title', models.CharField(max_length=500)),
                ('article_url', models.URLField(max_length=800, unique=True)),
                ('article_date', models.DateTimeField()),
                ('excerpt', models.TextField(blank=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(choices=[('positive', 'Pozitivno'), ('negative', 'Negativno'), ('neutral', 'Neutralno')], default='neutral', max_length=10)),
                ('mention_count', models.PositiveSmallIntegerField(default=1)),
                ('figure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='politics.politicalfigure')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='politics.politicalparty')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='politics.mediaportal')),
            ],
            options={
                'verbose_name': 'Pomen',
                'verbose_name_plural': 'Pomeni',
                'ordering': ['-article_date'],
                'indexes': [models.Index(fields=['figure', 'article_date'], name='politics_po_figure__b98199_idx'), models.Index(fields=['portal', 'article_date'], name='politics_po_portal__b4263b_idx'), models.Index(fields=['sentiment_label'], name='politics_po_sentime_899c1c_idx')],
            },
        ),
    ]
