# Generated by Django 4.2.29 on 2026-04-02 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(choices=[('BA', 'Bosnia & Herzegovina'), ('RS', 'Serbia')], max_length=2)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='banks/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=10)),
                ('records_found', models.PositiveSmallIntegerField(default=0)),
                ('records_updated', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_logs', to='calculators.bank')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calc_type', models.CharField(choices=[('loan', 'Loan Calculator'), ('mortgage', 'Mortgage Calculator'), ('investment', 'Investment Return'), ('savings', 'Savings Goal')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('inputs_json', models.JSONField()),
                ('results_json', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterestRateOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_type', models.CharField(choices=[('housing', 'Housing / Mortgage Loan'), ('consumer', 'Consumer Loan'), ('auto', 'Auto Loan'), ('business', 'Business Loan'), ('refinancing', 'Refinancing')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate %', max_digits=5)),
                ('rate_type', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable'), ('mixed', 'Fixed+Variable')], default='fixed', max_length=10)),
                ('ert', models.DecimalField(blank=True, decimal_places=2, help_text='Effective rate (ERT/EKS) %', max_digits=5, null=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_term_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_term_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('BAM', 'BAM'), ('EUR', 'EUR'), ('RSD', 'RSD')], default='BAM', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_offers', to='calculators.bank')),
            ],
            options={
                'ordering': ['loan_type', 'rate'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['base_currency', 'target_currency'],
                'unique_together': {('base_currency', 'target_currency')},
            },
        ),
    ]
