# Generated by Django 4.2.29 on 2026-04-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0003_add_more_banks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestrateoffer',
            name='loan_type',
            field=models.CharField(choices=[('stambeni', 'Stambeni kredit'), ('gotovinski', 'Gotovinski kredit'), ('auto', 'Auto kredit'), ('penzionerski', 'Penzionerski kredit'), ('potrosacki', 'Potrošački kredit'), ('refinansiranje', 'Refinansiranje'), ('poslovni', 'Poslovni kredit')], max_length=20),
        ),
    ]
